site_name: Zooniverse Help
site_url: https://help.zooniverse.org
site_description: How to do things in the Zooniverse.
repo_url: https://github.com/zooniverse/help/
theme:
  name: material
  logo: img/zooniverse.svg
  favicon: https://static.zooniverse.org/www.zooniverse.org/favicon.ico
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - social

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - 'Getting Started':
    - getting-started/index.md
    - getting-started/example.md
    - getting-started/glossary.md
    - getting-started/lab-policies.md
  - 'Best Practices': 
    - best-practices/index.md
    - best-practices/1-great-project.md
    - best-practices/2-launch-rush.md
    - best-practices/3-long-haul.md
    - best-practices/4-resources.md
  - 'Next Steps':
    - next-steps/caesar-realtime-data-processing.md
    - next-steps/data-analysis.md 
    - next-steps/data-exports.md
    - next-steps/experimental-features.md
    - next-steps/hosting-your-own-subject-media.md
    - next-steps/markdown.md
    - next-steps/newsletters.md
    - next-steps/subject-selection.md
  - 'Transcription Project Guide':
    - transcription-project-guide/index.md
    - transcription-project-guide/project-data.md
    - transcription-project-guide/workflows.md
    - transcription-project-guide/designing-for-volunteers.md
    - transcription-project-guide/beta-testing.md
    - transcription-project-guide/project-launch.md
    - transcription-project-guide/working-with-data.md 
    - transcription-project-guide/project-maintenance-and-conclusion.md
    - transcription-project-guide/acknowledgements-and-resources.md